language: objective-c
script:
- xcodebuild -workspace libtinyspline.xcodeproj/project.xcworkspace -scheme libtinyspline
  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  email:
    recipients:
    - builds@helplightning.com
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: elMvJSDk41APE3NPlSUSW3GN/Dm2AjrJrxi6FkR79En6fmOvp77dXd/R22gutfDpXHHfpsal37mch+f9brMH3dXAAEX0fmPiDTtHrUOmKoFw//HmrIgC7malw6pfcyYJX+xvU0dfV6HpTfXKzCYT3nwHt+0/8kUiPmVgAypMRzvo8EOZM5JvAIgNUXqtxZ/GXqP/uQK323wYOXCcNmwuKqK30PXajQaD/AofcI/bUPkaLhHKcbfKco+8OCWMlSTo5JLZKSKMGeDjar4Zo/9Gr5uePtKGZBKnpprQz5aXXROBG/e1LFEP62swifP1P6Cs5yKcyfSeuhRR4Pu86zIDq3IHbNlYusS97iprLNZiFVXTZgBlxTWMKDaZmeVov1KF8yRG6NgImw2FcjvvYDPcPDnuXInZ26F9HX06iortLuH56v+AAYIy74b21gv+cEu5xdZSdOw1Hkezxa8e6ZyRoy1S9dxiC22AoMbCdQx5awUyrNmuLOdtYxJCRo/wFxXR/u6s8Ns15Q6vokcD4BoOZTreagOmvsZxflyUH/GWYGLtcP2Dr8Ev/yLSXld2oEyxSjPgUdl1ARrBtvGlZjt2QxSmnumZme4AJjfl7DL4CJIO9Hv1aSd1JIEgibvM75kecPoyIVeF2ls7BRWGeDD3fQkMt4kkWdjdhRrnPKsx588=
